spring:
  application:
    name: cicdwithjava
  datasource:
    url: jdbc:postgresql://localhost:5432/test1
    username: postgres
    password: tere1234
  jpa:
    hibernate:
      ddl-auto: update   # dev only; use migrations in production
    show-sql: true
server:
  port: 8080